name: jekyll build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.3'
      - name: jekyll build
        run: bundle exec jekyll build --trace
      - name: trigger update
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: 'curl -fL -H "X-Deploy-Token: ${DEPLOY_TOKEN}" ${{ secrets.UPDATE_URL }}'
